name: mada_app
packages:
  - apps/*
  - packages/*

scripts:
  build:
    description: Build code generation for all packages
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
  analyze:
    description: Analyze all packages
    run: melos exec -- flutter analyze
  test:
    description: Run tests for all packages
    run: melos exec -- flutter test

